"""
Auto-generated comprehensive OCI Resource Type Mappings

This file contains deletion configurations for all major OCI resource types.
Generated by generate_comprehensive_mappings.py

Each resource type includes:
- client: The OCI SDK client class path
- method: The deletion method name
- id_field: The field name for resource ID
- composite: (optional) Composite client for wait operations
- composite_method: (optional) Method for wait operations
- wait_states: (optional) States to wait for
- dependencies: (optional) Resources that must be deleted first
- special: (optional) Special handling required
"""

RESOURCE_TYPE_MAP = {
    'Alarm': {
        'client': 'monitoring.MonitoringClient',
        'method': 'delete_alarm',
        'id_field': 'id',
    },
    'AnalyticsInstance': {
        'client': 'analytics.AnalyticsClient',
        'method': 'delete_analytics_instance',
        'id_field': 'id',
    },
    'Api': {
        'client': 'apigateway.ApiClient',
        'method': 'delete_api',
        'id_field': 'id',
    },
    'ApiDeployment': {
        'client': 'apigateway.DeploymentClient',
        'method': 'delete_deployment',
        'id_field': 'id',
    },
    'ApiGateway': {
        'client': 'apigateway.GatewayClient',
        'method': 'delete_gateway',
        'id_field': 'id',
    },
    'Application': {
        'client': 'functions.FunctionsManagementClient',
        'method': 'delete_application',
        'id_field': 'id',
        'dependencies': ['Function'],
    },
    'AutoScalingConfiguration': {
        'client': 'autoscaling.AutoScalingClient',
        'method': 'delete_auto_scaling_configuration',
        'id_field': 'id',
    },
    'AutonomousContainerDatabase': {
        'client': 'database.DatabaseClient',
        'method': 'terminate_autonomous_container_database',
        'id_field': 'id',
    },
    'AutonomousDatabase': {
        'client': 'database.DatabaseClient',
        'method': 'delete_autonomous_database',
        'id_field': 'id',
    },
    'AutonomousExadataInfrastructure': {
        'client': 'database.DatabaseClient',
        'method': 'terminate_autonomous_exadata_infrastructure',
        'id_field': 'id',
    },
    'BackupDestination': {
        'client': 'database.DatabaseClient',
        'method': 'delete_backup_destination',
        'id_field': 'id',
    },
    'Bastion': {
        'client': 'bastion.BastionClient',
        'method': 'delete_bastion',
        'id_field': 'id',
    },
    'BootVolume': {
        'client': 'core.BlockstorageClient',
        'method': 'delete_boot_volume',
        'id_field': 'id',
        'composite': 'core.BlockstorageClientCompositeOperations',
        'composite_method': 'delete_boot_volume_and_wait_for_state',
        'wait_states': ['TERMINATED'],
    },
    'BootVolumeAttachment': {
        'client': 'core.ComputeClient',
        'method': 'detach_boot_volume',
        'id_field': 'id',
    },
    'BootVolumeBackup': {
        'client': 'core.BlockstorageClient',
        'method': 'delete_boot_volume_backup',
        'id_field': 'id',
    },
    'Bucket': {
        'client': 'object_storage.ObjectStorageClient',
        'method': 'delete_bucket',
        'id_field': 'id',
        'special': 'bucket',
    },
    'BuildPipeline': {
        'client': 'devops.DevopsClient',
        'method': 'delete_build_pipeline',
        'id_field': 'id',
    },
    'Certificate': {
        'client': 'certificates_management.CertificatesManagementClient',
        'method': 'schedule_certificate_deletion',
        'id_field': 'id',
    },
    'CertificateAuthority': {
        'client': 'certificates_management.CertificatesManagementClient',
        'method': 'schedule_certificate_authority_deletion',
        'id_field': 'id',
    },
    'CloudExadataInfrastructure': {
        'client': 'database.DatabaseClient',
        'method': 'delete_cloud_exadata_infrastructure',
        'id_field': 'id',
    },
    'CloudGuardDetectorRecipe': {
        'client': 'cloud_guard.CloudGuardClient',
        'method': 'delete_detector_recipe',
        'id_field': 'id',
    },
    'CloudGuardManagedList': {
        'client': 'cloud_guard.CloudGuardClient',
        'method': 'delete_managed_list',
        'id_field': 'id',
    },
    'CloudGuardResponderRecipe': {
        'client': 'cloud_guard.CloudGuardClient',
        'method': 'delete_responder_recipe',
        'id_field': 'id',
    },
    'CloudGuardTarget': {
        'client': 'cloud_guard.CloudGuardClient',
        'method': 'delete_target',
        'id_field': 'id',
    },
    'CloudVmCluster': {
        'client': 'database.DatabaseClient',
        'method': 'delete_cloud_vm_cluster',
        'id_field': 'id',
    },
    'Cluster': {
        'client': 'container_engine.ContainerEngineClient',
        'method': 'delete_cluster',
        'id_field': 'id',
    },
    'ClusterNetwork': {
        'client': 'compute_management.ComputeManagementClient',
        'method': 'terminate_cluster_network',
        'id_field': 'id',
    },
    'Compartment': {
        'client': 'identity.IdentityClient',
        'method': 'delete_compartment',
        'id_field': 'id',
        'special': 'compartment',
    },
    'ConfigurationSourceProvider': {
        'client': 'resource_manager.ResourceManagerClient',
        'method': 'delete_configuration_source_provider',
        'id_field': 'id',
    },
    'ConnectHarness': {
        'client': 'streaming.StreamAdminClient',
        'method': 'delete_connect_harness',
        'id_field': 'id',
    },
    'ConsoleHistory': {
        'client': 'core.ComputeClient',
        'method': 'delete_console_history',
        'id_field': 'id',
    },
    'ContainerInstance': {
        'client': 'container_instances.ContainerInstanceClient',
        'method': 'delete_container_instance',
        'id_field': 'id',
    },
    'Cpe': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_cpe',
        'id_field': 'id',
    },
    'CustomerDnsZone': {
        'client': 'dns.DnsClient',
        'method': 'delete_zone',
        'id_field': 'id',
    },
    'DHCPOptions': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_dhcp_options',
        'id_field': 'id',
    },
    'DataCatalog': {
        'client': 'data_catalog.DataCatalogClient',
        'method': 'delete_catalog',
        'id_field': 'id',
    },
    'DataScienceModel': {
        'client': 'data_science.DataScienceClient',
        'method': 'delete_model',
        'id_field': 'id',
    },
    'DataScienceModelDeployment': {
        'client': 'data_science.DataScienceClient',
        'method': 'delete_model_deployment',
        'id_field': 'id',
    },
    'DataScienceNotebookSession': {
        'client': 'data_science.DataScienceClient',
        'method': 'delete_notebook_session',
        'id_field': 'id',
    },
    'DataScienceProject': {
        'client': 'data_science.DataScienceClient',
        'method': 'delete_project',
        'id_field': 'id',
    },
    'DbHome': {
        'client': 'database.DatabaseClient',
        'method': 'delete_db_home',
        'id_field': 'id',
    },
    'DbSystem': {
        'client': 'database.DatabaseClient',
        'method': 'terminate_db_system',
        'id_field': 'id',
    },
    'DedicatedVmHost': {
        'client': 'core.ComputeClient',
        'method': 'delete_dedicated_vm_host',
        'id_field': 'id',
    },
    'DeployPipeline': {
        'client': 'devops.DevopsClient',
        'method': 'delete_deployment_pipeline',
        'id_field': 'id',
    },
    'DevopsProject': {
        'client': 'devops.DevopsClient',
        'method': 'delete_project',
        'id_field': 'id',
    },
    'DevopsRepository': {
        'client': 'devops.DevopsClient',
        'method': 'delete_repository',
        'id_field': 'id',
    },
    'DisWorkspace': {
        'client': 'data_integration.DataIntegrationClient',
        'method': 'delete_workspace',
        'id_field': 'id',
    },
    'DnsResolver': {
        'client': 'dns.DnsClient',
        'method': 'delete_resolver',
        'id_field': 'id',
    },
    'DnsView': {
        'client': 'dns.DnsClient',
        'method': 'delete_view',
        'id_field': 'id',
    },
    'Drg': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_drg',
        'id_field': 'id',
    },
    'DrgAttachment': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_drg_attachment',
        'id_field': 'id',
    },
    'DrgRouteDistribution': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_drg_route_distribution',
        'id_field': 'id',
    },
    'DrgRouteTable': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_drg_route_table',
        'id_field': 'id',
    },
    'DynamicResourceGroup': {
        'client': 'identity.IdentityClient',
        'method': 'delete_dynamic_group',
        'id_field': 'id',
    },
    'EventsRule': {
        'client': 'events.EventsClient',
        'method': 'delete_rule',
        'id_field': 'id',
    },
    'EventRule': {  # Alias for EventsRule (OCI Search returns singular form)
        'client': 'events.EventsClient',
        'method': 'delete_rule',
        'id_field': 'id',
    },
    'ExadataInfrastructure': {
        'client': 'database.DatabaseClient',
        'method': 'delete_exadata_infrastructure',
        'id_field': 'id',
    },
    'Export': {
        'client': 'file_storage.FileStorageClient',
        'method': 'delete_export',
        'id_field': 'id',
    },
    'ExportSet': {
        'client': 'file_storage.FileStorageClient',
        'method': 'delete_export_set',
        'id_field': 'id',
    },
    'FileSystem': {
        'client': 'file_storage.FileStorageClient',
        'method': 'delete_file_system',
        'id_field': 'id',
    },
    'FssReplicationTarget': {
        'client': 'file_storage.FileStorageClient',
        'method': 'delete_replication_target',
        'id_field': 'id',
    },
    'Function': {
        'client': 'functions.FunctionsManagementClient',
        'method': 'delete_function',
        'id_field': 'id',
    },
    'GoldenGateDatabaseRegistration': {
        'client': 'golden_gate.GoldenGateClient',
        'method': 'delete_database_registration',
        'id_field': 'id',
    },
    'GoldenGateDeployment': {
        'client': 'golden_gate.GoldenGateClient',
        'method': 'delete_deployment',
        'id_field': 'id',
    },
    'Group': {
        'client': 'identity.IdentityClient',
        'method': 'delete_group',
        'id_field': 'id',
    },
    'IPSecConnection': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_ip_sec_connection',
        'id_field': 'id',
    },
    'IdentityProvider': {
        'client': 'identity.IdentityClient',
        'method': 'delete_identity_provider',
        'id_field': 'id',
    },
    'Image': {
        'client': 'core.ComputeClient',
        'method': 'delete_image',
        'id_field': 'id',
        'composite': 'core.ComputeClientCompositeOperations',
        'composite_method': 'delete_image_and_wait_for_state',
        'wait_states': ['DELETED'],
    },
    'Instance': {
        'client': 'core.ComputeClient',
        'method': 'terminate_instance',
        'id_field': 'id',
        'composite': 'core.ComputeClientCompositeOperations',
        'composite_method': 'terminate_instance_and_wait_for_state',
        'wait_states': ['TERMINATED'],
    },
    'InstanceConfiguration': {
        'client': 'compute_management.ComputeManagementClient',
        'method': 'delete_instance_configuration',
        'id_field': 'id',
    },
    'InstancePool': {
        'client': 'compute_management.ComputeManagementClient',
        'method': 'terminate_instance_pool',
        'id_field': 'id',
    },
    'IntegrationInstance': {
        'client': 'integration.IntegrationInstanceClient',
        'method': 'delete_integration_instance',
        'id_field': 'id',
    },
    'InternetGateway': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_internet_gateway',
        'id_field': 'id',
    },
    'Key': {
        'client': 'key_management.KmsManagementClient',
        'method': 'schedule_key_deletion',
        'id_field': 'id',
        'special': 'key',
    },
    'LoadBalancer': {
        'client': 'load_balancer.LoadBalancerClient',
        'method': 'delete_load_balancer',
        'id_field': 'id',
    },
    'LocalPeeringGateway': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_local_peering_gateway',
        'id_field': 'id',
    },
    'Log': {
        'client': 'logging.LoggingManagementClient',
        'method': 'delete_log',
        'id_field': 'id',
    },
    'LogAnalyticsEntity': {
        'client': 'log_analytics.LogAnalyticsClient',
        'method': 'delete_log_analytics_entity',
        'id_field': 'id',
        'special': 'log_analytics_entity'  # Needs namespace
    },
    'LogAnalyticsLogGroup': {
        'client': 'log_analytics.LogAnalyticsClient',
        'method': 'delete_log_analytics_log_group',
        'id_field': 'id',
    },
    'LogGroup': {
        'client': 'logging.LoggingManagementClient',
        'method': 'delete_log_group',
        'id_field': 'id',
    },
    'MountTarget': {
        'client': 'file_storage.FileStorageClient',
        'method': 'delete_mount_target',
        'id_field': 'id',
    },
    'MysqlBackup': {
        'client': 'mysql.DbBackupsClient',
        'method': 'delete_backup',
        'id_field': 'id',
    },
    'MysqlChannel': {
        'client': 'mysql.ChannelsClient',
        'method': 'delete_channel',
        'id_field': 'id',
    },
    'MysqlDbSystem': {
        'client': 'mysql.DbSystemClient',
        'method': 'delete_db_system',
        'id_field': 'id',
    },
    'NatGateway': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_nat_gateway',
        'id_field': 'id',
    },
    'NetworkLoadBalancer': {
        'client': 'network_load_balancer.NetworkLoadBalancerClient',
        'method': 'delete_network_load_balancer',
        'id_field': 'id',
    },
    'NetworkSecurityGroup': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_network_security_group',
        'id_field': 'id',
    },
    'NetworkSource': {
        'client': 'identity.IdentityClient',
        'method': 'delete_network_source',
        'id_field': 'id',
    },
    'NoSqlTable': {
        'client': 'nosql.NosqlClient',
        'method': 'delete_table',
        'id_field': 'id',
    },
    'NodePool': {
        'client': 'container_engine.ContainerEngineClient',
        'method': 'delete_node_pool',
        'id_field': 'id',
    },
    'OnsSubscription': {
        'client': 'ons.NotificationDataPlaneClient',
        'method': 'delete_subscription',
        'id_field': 'id',
    },
    'OnsTopic': {
        'client': 'ons.NotificationControlPlaneClient',
        'method': 'delete_topic',
        'id_field': 'id',
    },
    'OpensearchCluster': {
        'client': 'opensearch.OpensearchClusterClient',
        'method': 'delete_opensearch_cluster',
        'id_field': 'id',
    },
    'OrmStack': {
        'client': 'resource_manager.ResourceManagerClient',
        'method': 'delete_stack',
        'id_field': 'id',
    },
    'Policy': {
        'client': 'identity.IdentityClient',
        'method': 'delete_policy',
        'id_field': 'id',
    },
    'PostgresqlBackup': {
        'client': 'psql.PostgresqlClient',
        'method': 'delete_backup',
        'id_field': 'id',
    },
    'PostgresqlDbSystem': {
        'client': 'psql.PostgresqlClient',
        'method': 'delete_db_system',
        'id_field': 'id',
    },
    'PreauthenticatedRequest': {
        'client': 'object_storage.ObjectStorageClient',
        'method': 'delete_preauthenticated_request',
        'id_field': 'id',
        'special': 'bucket',
    },
    'PrivateIp': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_private_ip',
        'id_field': 'id',
    },
    'PublicIp': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_public_ip',
        'id_field': 'id',
    },
    'RedisCluster': {
        'client': 'redis.RedisClusterClient',
        'method': 'delete_redis_cluster',
        'id_field': 'id',
    },
    'RemotePeeringConnection': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_remote_peering_connection',
        'id_field': 'id',
    },
    'Replication': {
        'client': 'file_storage.FileStorageClient',
        'method': 'delete_replication',
        'id_field': 'id',
    },
    'RouteTable': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_route_table',
        'id_field': 'id',
    },
    'SecurityList': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_security_list',
        'id_field': 'id',
    },
    'ServiceConnector': {
        'client': 'sch.ServiceConnectorClient',
        'method': 'delete_service_connector',
        'id_field': 'id',
    },
    'ServiceGateway': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_service_gateway',
        'id_field': 'id',
    },
    'SteeringPolicy': {
        'client': 'dns.DnsClient',
        'method': 'delete_steering_policy',
        'id_field': 'id',
    },
    'SteeringPolicyAttachment': {
        'client': 'dns.DnsClient',
        'method': 'delete_steering_policy_attachment',
        'id_field': 'id',
    },
    'Stream': {
        'client': 'streaming.StreamAdminClient',
        'method': 'delete_stream',
        'id_field': 'id',
    },
    'StreamPool': {
        'client': 'streaming.StreamAdminClient',
        'method': 'delete_stream_pool',
        'id_field': 'id',
    },
    'Subnet': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_subnet',
        'id_field': 'id',
    },
    'TsigKey': {
        'client': 'dns.DnsClient',
        'method': 'delete_tsig_key',
        'id_field': 'id',
    },
    'User': {
        'client': 'identity.IdentityClient',
        'method': 'delete_user',
        'id_field': 'id',
    },
    'Vault': {
        'client': 'key_management.KmsVaultClient',
        'method': 'schedule_vault_deletion',
        'id_field': 'id',
        'special': 'vault',
    },
    'VbInstance': {
        'client': 'visual_builder.VbInstanceClient',
        'method': 'delete_vb_instance',
        'id_field': 'id',
    },
    'Vcn': {
        'client': 'core.VirtualNetworkClient',
        'method': 'delete_vcn',
        'id_field': 'id',
        'dependencies': ['Subnet', 'InternetGateway', 'NatGateway', 'ServiceGateway', 'RouteTable', 'SecurityList', 'LocalPeeringGateway'],
    },
    'VmCluster': {
        'client': 'database.DatabaseClient',
        'method': 'delete_vm_cluster',
        'id_field': 'id',
    },
    'VmClusterNetwork': {
        'client': 'database.DatabaseClient',
        'method': 'delete_vm_cluster_network',
        'id_field': 'id',
    },
    'Volume': {
        'client': 'core.BlockstorageClient',
        'method': 'delete_volume',
        'id_field': 'id',
        'composite': 'core.BlockstorageClientCompositeOperations',
        'composite_method': 'delete_volume_and_wait_for_state',
        'wait_states': ['TERMINATED'],
    },
    'VolumeAttachment': {
        'client': 'core.ComputeClient',
        'method': 'detach_volume',
        'id_field': 'id',
    },
    'VolumeBackup': {
        'client': 'core.BlockstorageClient',
        'method': 'delete_volume_backup',
        'id_field': 'id',
    },
    'VolumeBackupPolicy': {
        'client': 'core.BlockstorageClient',
        'method': 'delete_volume_backup_policy',
        'id_field': 'id',
    },
    'VolumeGroup': {
        'client': 'core.BlockstorageClient',
        'method': 'delete_volume_group',
        'id_field': 'id',
    },
    'VolumeGroupBackup': {
        'client': 'core.BlockstorageClient',
        'method': 'delete_volume_group_backup',
        'id_field': 'id',
    },
}
